### ISSUE TITLE
Issue setting up the API

### ISSUE THREAD

**Issue by weisisheng** [MrHertal/react-admin-amplify-demo#11]
Kind of a noob at using APIs with appsync (i usually default to cognito pools only), would appreciate any advice.  I set up both a cognito pool and API access using "amplify add auth" but when I try to do my first push, I get the error "@auth directive with 'apiKey' provider found, but the project has no API Key authentication provider configured."

This is a great contribution!  I've spent a bit of time with the 17 graphql examples and looked over RA; the combo of the 2 will make for great study. Thanks in advance.

**Comment by MrHertal** [comment]
Hi, thanks for your message.

After adding auth with ‘amplify add auth’,
did you update your API to configure additional auth?

´amplify update api’

**Comment by weisisheng** [comment]
I did it somewhat backwards, removing the 
"User" directive/table creator and then installing cognito pools and api access. Then added back the "User" directive and the push works.  On to password issues since i removed the google recaptcha while I learn.  Thanks for the fast response.
