### ISSUE TITLE
Uncaught router error --> now "no current user" error

### ISSUE THREAD

**Issue by weisisheng** [MrHertal/react-admin-amplify-demo#17]
Revisiting this after a few months now that I understand R-A a bit better.  This is such an outstanding example application.

I went about commenting out the custom login page and removed the pre-auth trigger.  Now I get the following error:

<snip>
Uncaught (in promise) Could not find router reducer in state tree, it must be mounted under "router"
</snip>

regardless of whether I try it locally or pushed to amplify.  Welcome any advice.

Thanks in advance.

*** Using latest app code and @aws-amplify/core 3.6.0, @aws-amplify/auth 3.4.6, @aws-amplify/api 3.2.6,

**Comment by weisisheng** [comment]
This is part of it, a problem with history 5.0, reverting to 4.10.0 makes progress.

https://stackoverflow.com/questions/54315988/connectedrouter-error-could-not-find-router-reducer-in-state-tree-it-must-be-m

Now I have another error related to "no current user" but getting closer.

**Comment by weisisheng** [comment]
Reverted back from "latest" to the @aws modules found in the package.json and no change to the error.

**Comment by MrHertal** [comment]
Hi,

Are you trying to run the demo locally? If it's the case, check this guideline:

https://github.com/MrHertal/react-admin-amplify-demo#how-to-clone-this-project

**Comment by weisisheng** [comment]
Thanks for the fast response.  I did follow the instructions carefully and will give it another try and report back.  All the best.

**Comment by weisisheng** [comment]
Just following up, using all versions in the package.json and following the instructions carefully, the error "no current user, index.js" repeats and I can't login locally.  I will keep hacking away.  The complaint about "no current user" pops up in a few amplify forums.

**Comment by weisisheng** [comment]
Very strange, I initially skipped the step to "confirm user password" assuming I would get a field to do it later upon first login.  As an experiment, I confirmed with the CLI as suggested and I am in to the dashboard.  Solved for now although I need to dig into how users will access in future in a quick/easy way.
