### ISSUE TITLE
Workaround for pre auth trigger

### ISSUE THREAD

**Issue by fabraz** [MrHertal/react-admin-amplify-demo#27]
Hi @MrHertal!

Thanks for your demo. 

I was wondering whether you could give a help about the step for removing the pre auth trigger. I'm facing the issue reported [here](https://github.com/aws-amplify/amplify-cli/issues/2458). Therefore, amplify cli does not remove pre auth, though the login cant work, without reCaptcha properly configured.

Thanks in advance!

**Comment by MrHertal** [comment]
Hi @fabraz,

Did you follow [these steps](https://github.com/MrHertal/react-admin-amplify-demo#how-to-clone-this-project)?

Could you show the error you got?

Thanks

**Comment by MrHertal** [comment]
OK I was able to reproduce.

This is weird because I could remove the trigger before.

It is not working anymore with Amplify CLI 4.41.2

**Comment by MrHertal** [comment]
I wanted to remove that trigger anyway because I realized that ReCaptcha is useless here.

I had no choice but to recreate the all Amplify backend...

@fabraz you can now clone the demo project, thanks for reporting the issue.
