### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by nicolas-lescop** [MrHertal/react-admin-amplify-demo#30]
Hello, 

When I try the command `amplify init`

Looks like configuration for ios make it crash.

![9e336cf502830afd8c008e9b3c01f101 (1)](https://user-images.githubusercontent.com/1667009/107788370-9d5f1e80-6d50-11eb-9068-07f9ca7b336b.jpg)

**Comment by MrHertal** [comment]
Hi 👋 

This looks similar to that issue: https://github.com/aws-amplify/amplify-cli/issues/6508

Can you update your CLI to the last version?
