### ISSUE TITLE
Split system between admin and customer system?

### ISSUE THREAD

**Issue by BruceWheaton** [MrHertal/react-admin-amplify-demo#37]
The docs note that the repo can be separate from the AWS resources. Is that just a matter of including files from a different folder? So the admin repo would not have any amplify backend?

Thanks for sharing this work!

Bruce

**Comment by MrHertal** [comment]
Hi,

Yes it means that you can have any project that holds the Amplify resources (project with the `amplify` folder) and use this library in a separate repository. All you need to have to initialize react-admin are the queries and mutations + the `aws-exports` file.

**Comment by BruceWheaton** [comment]
Thanks - that's what I hoped: but what's the mechanism? Copy the files from the other project? Can it co-exist with an amplify project (for instance to use hosting) in the admin app?

**Comment by MrHertal** [comment]
You need to copy the queries, mutations and the `aws-exports` file from the other project.
These are the files required in order to init [AmplifyAdmin](https://github.com/MrHertal/react-admin-amplify#usage)

Yes it can co-exist with an Amplify folder in the admin app.
